=== cdsframework/ice-test-manager/cat-support-xml/src/main/resources/catMenu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    The CAT support XML project generates xml-based artifacts for the CDS Framework.

    Copyright (C) 2016 New York City Department of Health and Mental Hygiene, Bureau of Immunization
    Contributions by HLN Consulting, LLC

    This program is free software: you can redistribute it and/or modify it under the terms of the GNU
    Lesser General Public License as published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version. You should have received a copy of the GNU Lesser
    General Public License along with this program. If not, see <http://www.gnu.org/licenses/> for more
    details.

    The above-named contributors (HLN Consulting, LLC) are also licensed by the New York City
    Department of Health and Mental Hygiene, Bureau of Immunization to have (without restriction,
    limitation, and warranty) complete irrevocable access and rights to this project.

    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; THE
    SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
    BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS, IF ANY, OR DEVELOPERS BE LIABLE FOR
    ANY CLAIM, DAMAGES, OR OTHER LIABILITY OF ANY KIND, ARISING FROM, OUT OF, OR IN CONNECTION WITH
    THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

    For more information about this software, see https://www.hln.com/services/open-source/ or send
    correspondence to ice@hln.com.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://menu.cdsframework.org" targetNamespace="http://menu.cdsframework.org">
    <xs:element name="pluginName" type="xs:string"/>
    <xs:element name="menuName" type="xs:string"/>
    <xs:element name="menuItemName" type="xs:string"/>
    <xs:element name="viewName" type="xs:string"/>
    <xs:element name="menuItemType" type="xs:string"/>
    <xs:element name="permissionType" type="xs:string"/>
    <xs:element name="permissionClass" type="xs:string"/>
    <xs:complexType name="MenuItem">
        <xs:sequence>
            <xs:element ref="ns1:menuItemName" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="ns1:viewName" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="ns1:menuItemType" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="ns1:permissionType" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="ns1:permissionClass" minOccurs="0" maxOccurs="1"/>
            <xs:element name="menuItem" type="ns1:MenuItem" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Menu">
        <xs:sequence>
            <xs:element ref="ns1:menuName" minOccurs="1" maxOccurs="1"/>
            <xs:element name="menuItem" type="ns1:MenuItem" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Menus">
        <xs:sequence>
            <xs:element ref="ns1:pluginName" minOccurs="1" maxOccurs="1"/>
            <xs:element name="menu" type="ns1:Menu" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="catMenus" type="ns1:Menus"/>
</xs:schema>

=== cdsframework/ice-test-manager/cat-support-cds/src/main/resources/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    CAT CDS support plugin project.

    Copyright (C) 2016 New York City Department of Health and Mental Hygiene, Bureau of Immunization
    Contributions by HLN Consulting, LLC

    This program is free software: you can redistribute it and/or modify it under the terms of the GNU
    Lesser General Public License as published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version. You should have received a copy of the GNU Lesser
    General Public License along with this program. If not, see <http://www.gnu.org/licenses/> for more
    details.

    The above-named contributors (HLN Consulting, LLC) are also licensed by the New York City
    Department of Health and Mental Hygiene, Bureau of Immunization to have (without restriction,
    limitation, and warranty) complete irrevocable access and rights to this project.

    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; THE

    SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
    BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS, IF ANY, OR DEVELOPERS BE LIABLE FOR
    ANY CLAIM, DAMAGES, OR OTHER LIABILITY OF ANY KIND, ARISING FROM, OUT OF, OR IN CONNECTION WITH
    THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

    For more information about this software, see https://www.hln.com/services/open-source/ or send
    correspondence to ice@hln.com.

-->
<ns1:catMenus
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://menu.cdsframework.org'
    xsi:schemaLocation='http://menu.cdsframework.org ../../../../../cdsframework-core-service/cat-support-xml/src/main/resources/catMenu.xsd'>
    <ns1:pluginName>cds</ns1:pluginName>
    <menu>
        <ns1:menuName>CDS Data Manager</ns1:menuName>
        <menuItem>
            <ns1:menuItemName>Code System Editor</ns1:menuItemName>
            <ns1:viewName>cdsCodeSystemMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.CdsCodeSystemDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Value Set Editor</ns1:menuItemName>
            <ns1:viewName>valueSetMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.ValueSetDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Concept Manager</ns1:menuItemName>
            <ns1:menuItemType>SUBMENU</ns1:menuItemType>
            <menuItem>
                <ns1:menuItemName>Concept Editor</ns1:menuItemName>
                <ns1:viewName>conceptMGR.jsf</ns1:viewName>
                <ns1:menuItemType>LINK</ns1:menuItemType>
                <ns1:permissionType>FULL</ns1:permissionType>
                <ns1:permissionClass>org.cdsframework.dto.OpenCdsConceptDTO</ns1:permissionClass>
            </menuItem>
            <menuItem>
                <ns1:menuItemName>Concept Determination Method Editor</ns1:menuItemName>
                <ns1:viewName>conceptDeterminationMethodMGR.jsf</ns1:viewName>
                <ns1:menuItemType>LINK</ns1:menuItemType>
                <ns1:permissionType>FULL</ns1:permissionType>
                <ns1:permissionClass>org.cdsframework.dto.ConceptDeterminationMethodDTO</ns1:permissionClass>
            </menuItem>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Misc</ns1:menuItemName>
            <ns1:menuItemType>SEPARATOR</ns1:menuItemType>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>List Editor</ns1:menuItemName>
            <ns1:viewName>listMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.CdsListDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Misc</ns1:menuItemName>
            <ns1:menuItemType>SEPARATOR</ns1:menuItemType>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Data Model Editor</ns1:menuItemName>
            <ns1:viewName>dataModelMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.DataModelDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Misc</ns1:menuItemName>
            <ns1:menuItemType>SEPARATOR</ns1:menuItemType>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Data Template Editor</ns1:menuItemName>
            <ns1:viewName>dataTemplateMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.DataTemplateDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Misc</ns1:menuItemName>
            <ns1:menuItemType>SEPARATOR</ns1:menuItemType>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Criteria Resource Editor</ns1:menuItemName>
            <ns1:viewName>criteriaResourceMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.CriteriaResourceDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Misc</ns1:menuItemName>
            <ns1:menuItemType>SEPARATOR</ns1:menuItemType>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Criteria Editor</ns1:menuItemName>
            <ns1:viewName>criteriaMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.CriteriaDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Misc</ns1:menuItemName>
            <ns1:menuItemType>SEPARATOR</ns1:menuItemType>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Knowledge Module Editor</ns1:menuItemName>
            <ns1:viewName>cdsBusinessScopeMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.CdsBusinessScopeDTO</ns1:permissionClass>
        </menuItem>
    </menu>
  </ns1:catMenus>

=== cdsframework/ice-test-manager/cat-ice-primefaces/src/main/resources/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    CAT ICE support plugin project.

    Copyright (C) 2016 New York City Department of Health and Mental Hygiene, Bureau of Immunization
    Contributions by HLN Consulting, LLC

    This program is free software: you can redistribute it and/or modify it under the terms of the GNU
    Lesser General Public License as published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version. You should have received a copy of the GNU Lesser
    General Public License along with this program. If not, see <http://www.gnu.org/licenses/> for more
    details.

    The above-named contributors (HLN Consulting, LLC) are also licensed by the New York City
    Department of Health and Mental Hygiene, Bureau of Immunization to have (without restriction,
    limitation, and warranty) complete irrevocable access and rights to this project.

    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; THE

    SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
    BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS, IF ANY, OR DEVELOPERS BE LIABLE FOR
    ANY CLAIM, DAMAGES, OR OTHER LIABILITY OF ANY KIND, ARISING FROM, OUT OF, OR IN CONNECTION WITH
    THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

    For more information about this software, see https://www.hln.com/services/open-source/ or send
    correspondence to ice@hln.com.

-->
<ns1:catMenus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:ns1="http://menu.cdsframework.org"
              xsi:schemaLocation="http://menu.cdsframework.org ../../../../../cdsframework-core-service/cat-support-xml/src/main/resources/catMenu.xsd">
    <ns1:pluginName>ice</ns1:pluginName>
    <menu>
        <ns1:menuName>ICE Manager</ns1:menuName>
        <menuItem>
            <ns1:menuItemName>Supporting Data Manager</ns1:menuItemName>
            <ns1:menuItemType>SUBMENU</ns1:menuItemType>
            <menuItem>
                <ns1:menuItemName>Disease Editor</ns1:menuItemName>
                <ns1:viewName>iceDiseaseMGR.jsf</ns1:viewName>
                <ns1:menuItemType>LINK</ns1:menuItemType>
                <ns1:permissionType>FULL</ns1:permissionType>
                <ns1:permissionClass>org.cdsframework.dto.IceDiseaseDTO</ns1:permissionClass>
            </menuItem>
            <menuItem>
                <ns1:menuItemName>Vaccine Component Editor</ns1:menuItemName>
                <ns1:viewName>iceVaccineComponentMGR.jsf</ns1:viewName>
                <ns1:menuItemType>LINK</ns1:menuItemType>
                <ns1:permissionType>FULL</ns1:permissionType>
                <ns1:permissionClass>org.cdsframework.dto.IceVaccineComponentDTO</ns1:permissionClass>
            </menuItem>
            <menuItem>
                <ns1:menuItemName>Vaccine Editor</ns1:menuItemName>
                <ns1:viewName>iceVaccineMGR.jsf</ns1:viewName>
                <ns1:menuItemType>LINK</ns1:menuItemType>
                <ns1:permissionType>FULL</ns1:permissionType>
                <ns1:permissionClass>org.cdsframework.dto.IceVaccineDTO</ns1:permissionClass>
            </menuItem>
            <menuItem>
                <ns1:menuItemName>Vaccine Group Editor</ns1:menuItemName>
                <ns1:viewName>iceVaccineGroupMGR.jsf</ns1:viewName>
                <ns1:menuItemType>LINK</ns1:menuItemType>
                <ns1:permissionType>FULL</ns1:permissionType>
                <ns1:permissionClass>org.cdsframework.dto.IceVaccineGroupDTO</ns1:permissionClass>
            </menuItem>
            <menuItem>
                <ns1:menuItemName>Series Editor</ns1:menuItemName>
                <ns1:viewName>iceSeriesMGR.jsf</ns1:viewName>
                <ns1:menuItemType>LINK</ns1:menuItemType>
                <ns1:permissionType>FULL</ns1:permissionType>
                <ns1:permissionClass>org.cdsframework.dto.IceSeriesDTO</ns1:permissionClass>
            </menuItem>
            <menuItem>
                <ns1:menuItemName>Season Editor</ns1:menuItemName>
                <ns1:viewName>iceSeasonMGR.jsf</ns1:viewName>
                <ns1:menuItemType>LINK</ns1:menuItemType>
                <ns1:permissionType>FULL</ns1:permissionType>
                <ns1:permissionClass>org.cdsframework.dto.IceSeasonDTO</ns1:permissionClass>
            </menuItem>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Test Editor</ns1:menuItemName>
            <ns1:viewName>iceTestMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.IceTestSuiteDTO</ns1:permissionClass>
        </menuItem>
    </menu>
</ns1:catMenus>

=== cdsframework/ice-test-manager/cat-support-core/src/main/resources/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    CAT Core support plugin project.

    Copyright (C) 2016 New York City Department of Health and Mental Hygiene, Bureau of Immunization
    Contributions by HLN Consulting, LLC

    This program is free software: you can redistribute it and/or modify it under the terms of the GNU
    Lesser General Public License as published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version. You should have received a copy of the GNU Lesser
    General Public License along with this program. If not, see <http://www.gnu.org/licenses/> for more
    details.

    The above-named contributors (HLN Consulting, LLC) are also licensed by the New York City
    Department of Health and Mental Hygiene, Bureau of Immunization to have (without restriction,
    limitation, and warranty) complete irrevocable access and rights to this project.

    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; THE
    SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
    BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS, IF ANY, OR DEVELOPERS BE LIABLE FOR
    ANY CLAIM, DAMAGES, OR OTHER LIABILITY OF ANY KIND, ARISING FROM, OUT OF, OR IN CONNECTION WITH
    THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

    For more information about this software, see https://www.hln.com/services/open-source/ or send
    correspondence to ice@hln.com.

-->
<ns1:catMenus
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://menu.cdsframework.org'
    xsi:schemaLocation='http://menu.cdsframework.org ../../../../cat-support-xml/src/main/resources/catMenu.xsd'>
    <ns1:pluginName>core</ns1:pluginName>
    <menu>
        <ns1:menuName>CAT Manager</ns1:menuName>
        <menuItem>
            <ns1:menuItemName>About</ns1:menuItemName>
            <ns1:viewName>systemInfo.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>SELECT</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.SessionDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Misc</ns1:menuItemName>
            <ns1:menuItemType>SEPARATOR</ns1:menuItemType>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>App Editor</ns1:menuItemName>
            <ns1:viewName>appMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.AppDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Property Editor</ns1:menuItemName>
            <ns1:viewName>propertyMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.SystemPropertyDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Security Editor</ns1:menuItemName>
            <ns1:viewName>schemeMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.SecuritySchemeDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Session Administration</ns1:menuItemName>
            <ns1:viewName>sessionMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.SessionDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>User Editor</ns1:menuItemName>
            <ns1:viewName>userMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.UserDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>Audit Administration</ns1:menuItemName>
            <ns1:viewName>auditLogMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.AuditTransactionDTO</ns1:permissionClass>
        </menuItem>
        <menuItem>
            <ns1:menuItemName>App Log Administration</ns1:menuItemName>
            <ns1:viewName>appLogMGR.jsf</ns1:viewName>
            <ns1:menuItemType>LINK</ns1:menuItemType>
            <ns1:permissionType>FULL</ns1:permissionType>
            <ns1:permissionClass>org.cdsframework.dto.AppLogDTO</ns1:permissionClass>
        </menuItem>
    </menu>
</ns1:catMenus>
